sudo: required
services:
  - docker
before_install: 
  - docker build -t fabiomendeslps/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true fabiomendeslps/react-test npm test
after_success: 
  - docker build -t fabiomendeslps/multi-client ./client
  - docker build -t fabiomendeslps/multi-nginx ./nginx
  - docker build -t fabiomendeslps/multi-server ./server
  - docker build -t fabiomendeslps/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fabiomendeslps/multi-client
  - docker push fabiomendeslps/multi-nginx
  - docker push fabiomendeslps/multi-server
  - docker push fabiomendeslps/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-228717509522"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"